[package]
name = "wonder-of-u-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
serde_json.workspace = true
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "default-themes", "regex-onig"] }
time.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
wonder-of-u-core.workspace = true
